### ISSUE TITLE
hope you can provide the code and commands for all the experiments mentioned in your paper

### ISSUE THREAD

**Issue by Yingfei-Wu** [JHang2020/PCM3#1]
Thank you very much for your outstanding work. Recently, I have been trying to reproduce your code, but I have been unable to replicate the results from your paper when performing retrieval results evaluation, semi-supervised evaluation, and other tasks on the NTU and PKU datasets, except for linear eval. The reproduction results for the PKU dataset are particularly unsatisfactory due to the lack of related commands. I would greatly appreciate it if you could provide the code and commands for the remaining tasks. Thank you very much!

**Comment by JHang2020** [comment]
Thanks for your attention! We are working on it, and the relevant retrieval, detection code will be released soon. 
Besides, for motion prediction, you can find the codebase here: https://github.com/una-dinosauria/human-motion-prediction.

**Comment by Yingfei-Wu** [comment]
> Thanks for your attention! We are working on it, and the relevant retrieval, detection code will be released soon. Besides, for motion prediction, you can find the codebase here: https://github.com/una-dinosauria/human-motion-prediction.

thank you so much!
